MVC/Models/GradeModel.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Threading.Tasks;

namespace MVC.Models
{
    public class GradeModel
    {
        // check to make sure inputs are between 0 and 100 and each field is complete
        [Range(0, 100, ErrorMessage = "Assignments must be between 0 and 100")]
        [Required]
        public double Assignments { get; set; }

        [Range(0, 100, ErrorMessage = "Group Projects must be between 0 and 100")]
        [Required]
        public double GP { get; set; }

        [Range(0, 100, ErrorMessage = "Quizzes must be between 0 and 100")]
        [Required]
        public double Quizzes { get; set; }

        [Range(0, 100, ErrorMessage = "Midterms must be between 0 and 100")]
        [Required]
        public double Midterms { get; set; }

        [Range(0, 100, ErrorMessage = "Final Exam grade must be between 0 and 100")]
        [Required]
        public double Final { get; set; }

        [Range(0, 100, ErrorMessage = "Intex grade must be between 0 and 100")]
        [Required]
        public double Intex { get; set; }
    }
}

MVC/Controllers/BlahController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using MVC.Models;


// For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860

namespace MVC.Controllers
{
    public class BlahController : Controller
    {
        // GET: /<controller>/
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult GradeCalc()
        {
            return View();
        }

        [HttpPost]
        public IActionResult GradeCalc(GradeModel model)
        {
            return View(model);
        }

    }
}

MVC/Views/Blah/GradeCalc.cshtml
@*
For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{

}

@model GradeModel;


<!--A "Grade Calculator" form that takes as input a percentage scored for each grade
category listed in the syllabus-->

<h3>IS 413 Grade Calculator</h3>
<p>Enter your percentage scored for each grade category</p>

<!--form for each grade-->
<form method="post">
    <label>Assignments: </label>
    <input id="assignments" asp-for="Assignments" /><br />
    <label>Group Projects: </label>
    <input id="gp" asp-for="GP" /><br />
    <label>Quizzes: </label>
    <input id="quizzes" asp-for="Quizzes" /><br />
    <label>Midterm Exam: </label>
    <input id="midterms" asp-for="Midterms" /><br />
    <label>Final Exam: </label>
    <input id="final" asp-for="Final" /><br />
    <label>INTEX: </label>
    <input id="intex" asp-for="Intex" /><br />

    <!--output any errors-->
    <div asp-validation-summary="All"></div>


    <br />
    <input id="btnSend" type="submit" value="Calculate" />
</form>

MVC/Views/Blah/Index.cshtml
@*

*@

@{
    ViewData["Title"] = "IS 413 is the best";
}


<!--Header that lists your preferred name-->
<header>
    <h1><i class="fa fa-cloud"></i> Amy Zhang <i class="fa fa-cloud"></i></h1>
    <h4>Welcome to my page</h4>
</header>

<!--A picture of yourself doing something you enjoy-->
<img id="picGanderson" src="img/fam.jpg" class="center" />
<h6>I enjoy spending time with my family and exploring the world</h6>

<!--A paragraph on what you hope to get out of this IS 413 class-->
<br />

<p>
    I am excited to learn more about C# and use it to build awesome web applications!
    I hope to build unity with my teammates as we work together on projects and accomplish
    what may seem impossible. I am excited to push myself and go beyong the scope of the class
    if possible in order to prepare myself for industry. I hope to continue to understand OOP
    and get more comfortable to MVC
</p>

<!--an ordered list of my top 3 jobs-->
<b><p>The Top #3 jobs I'm interested in pursuing</p></b>
<ol>
    <li>Data Analyst</li>
    <li>Software Developer</li>
    <li>Consultant</li>
</ol>

<br /><br /><br /><br />
    

MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <meta charset="utf-8" />

    <!--A webpage title-->
    <title>@ViewData["Title"]</title>

    <!--An icon for the website-->
    <link rel="icon" href="img/favicon.ico" type="image/x-icon" />


    <!--Style the site using Bootstrap.-->
    <link href="~/lib/bootstrap/css/bootstrap.min.css" rel="stylesheet" />
    <link href="~/css/default.css" rel="stylesheet" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

</head>

<body>
    <nav>
        <a asp-controller="Blah" asp-action="Index">Home</a>
        <a asp-controller="Blah" asp-action="GradeCalc">Grade Calc</a>
    </nav>

    <div>
        @RenderBody()
    </div>
    <footer>This is the footer :)</footer>
    <script src="~/lib/jquery/jquery-3.6.3.min.js"></script>
    <script src="~/lib/bootstrap/js/bootstrap.js"></script>
    <script src="~/js/grade.js"></script>


</body>

</html>